### ISSUE TITLE
Internatiolization

### ISSUE THREAD

**Issue by luizdepra** [meleca/mr-roboto#1]
Apply i18n.

**Comment by Abdur-rahmaanJ** [comment]
i can help with french

**Comment by julianolf** [comment]
Hey @Abdur-rahmaanJ.

> i can help with french

That would be great!

I think we should start by initialising a translation tool, marking all string messages and creating the POT file. This would be all for this issue. Then a new issue to add French support could be created.

PS.: By translation tool I mean making use of `gettext` module that I'm familiar with, but if you or anyone else knows a better Python library to deal with i18n I'm all ears.

**Comment by Abdur-rahmaanJ** [comment]
@julianolf see polib, fairly straightforward

**Comment by julianolf** [comment]
Guys, I've sent a suggestion for the i18n implementation using the [polib](https://polib.readthedocs.io) library. Any feedback is welcome. 🙂

**Comment by julianolf** [comment]
Well, as the PR #148 added i18n support and the PR #151 added portuguese translation as an example of translation I believe everything required by this issue has been done, so I'm going to close it.
