### ISSUE TITLE
Command about

### ISSUE THREAD

**Issue by julianolf** [meleca/mr-roboto#11]
A command to share some info about the bot and print its github project url.

**Comment by julianolf** [comment]
@bmeneguele @luizdepra any suggestion for the about message? I thought about something really simples like:

> Hi there, my name is _nickname_ and I am an IRC bot written in Python. If you wanna know more about me take a look at my Github page https://github.com/meleca/mr-roboto/.

**Comment by bmeneguele** [comment]
@julianolf sounds great. But I also think it would be worth to start to version the bot and deploy only those "released" versions, thus we could also print the version when !about is ran. But for that to work properly we must start to bump version numbers every time we reach a "milestone", maybe whenever an issue/feature is closed/completed. What do you guys think?

**Comment by julianolf** [comment]
Let's create an issue to discuss releases. And until we don't reach an agreement about it I'll keep the _about message_ as I've mentioned before.

**Comment by bmeneguele** [comment]
Looks good to me.
