### ISSUE TITLE
Getting URLs sent to channel

### ISSUE THREAD

**Issue by julianolf** [meleca/mr-roboto#12]
The url handler is raising an error when more than a single address is sent to the channel.

**Comment by bmeneguele** [comment]
How did you get this error? I tested throwing a bunch of links sequentially in a separated channel and nothing happened, they were handled just fine.

**Comment by luizdepra** [comment]
The problem seens to be more complicated than that. I reproduced it send a URL plus some random text.

**Comment by julianolf** [comment]
Basically when an url is sent preceded or followed by any other word the error pops up. Just because I've forgot to pick ONLY the url inside the handle_url method. :P

**Comment by bmeneguele** [comment]
Oh! Easy to solve then :D.

**Comment by julianolf** [comment]
It would be, but now I just can't reproduce the bug anymore. Can you guys? Please paste here the line that generates the error.

**Comment by bmeneguele** [comment]
I think I found a link.. indeed a really interesting one :D.

> 09:37:05         bmeneg | http://www.google.com.br/
> 09:37:06      mr_roboto | Booom shakalaka

**Comment by bmeneguele** [comment]
Este link também gera o erro:

` http://www.hardmob.com.br/promocoes/610478-saintc-and-a-gshock-269-00-369-00-10x-bonitos.html

**Comment by bmeneguele** [comment]
Ok, I might have found the issue.. it seems the problem is being caused due to html content encoded with another charset other than utf-8 and the default encoding('utf-8') is not being able to translate/force all chars from other charset (like latin-1), for whatever reason. The following change would solve the problem, but I'm not really comfortable working with charsets..... so what do you guys think?

plugins/behavior.py:
```python
  129         def handle_text(target, subtype, data):                                                                                                                                                                                                                         
! 130             try:                                                                                                                                                                                                                                                        
+ 131                 content = str(data, encoding='utf-8')                                                                                                                                                                                                                   
+ 132             except UnicodeDecodeError:                                                                                                                                                                                                                                  
+ 133                 # probably latin-1 encode was used                                                                                                                                                                                                                      
+ 134                 content = str(data, encoding='latin-1')  
```

**Comment by julianolf** [comment]
What if it's neither utf8 nor latin1?

IMHO we should handle the exception for anything different from utf8 by returning a message like "I'm sorry but I've received a response with a weird encoding from _`source_page`_." or something like that. 🤣

**Comment by bmeneguele** [comment]
Yes, indeed it would be a partial solution, I just considered it because our region (pt_BR, es_..) can basically be handled by latin-1, and most of the webpages will be or utf8 or latin1. We could handle both of them and then return something like you said to everything else.

**Comment by bmeneguele** [comment]
Ok, I'm going to code it and send a PR.. probably not today, but soon =).. thanks
