### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by julianolf** [meleca/mr-roboto#21]
* Adjust code style in order to comply to [flake8](http://flake8.pycqa.org);
* The comments must follow Google's Python [style guide](https://github.com/google/styleguide/blob/gh-pages/pyguide.md#38-comments-and-docstrings);
* Remove all unnecessary comments and files;
* Normalize code:
  * e.g.
    * Single quotes for strings and double quotes for docstrings;
    * Choose between string interpolation or text formatting functions.

**Comment by bmeneguele** [comment]
It seems that with these two merges (PR #29 and PR #32) this issue was solved and can be closed. Please feel free to reopen in case there is something else to be done regarding coding style.
