### ISSUE TITLE
Add handling for links on channel

### ISSUE THREAD

**Issue by julianolf** [meleca/mr-roboto#3]
Add a new behavior to print page title for all urls sent to the channel, and add this url into database for future reference.

**Comment by luizdepra** [comment]
Nop! Unfinished. Need to store links in database and create commands to list it.

**Comment by bmeneguele** [comment]
Do we really need a "link history"? Depending the size of this db, irc server might kick mr_roboto due to flooding during listing :laughing:

**Comment by julianolf** [comment]
I like the idea of keeping the links in order to retrieve those, specially if someone share something interesting when you are offline.

About flooding, we can retrieve just the last few (maybe 5) results and add filter options, like date and subject.

We could arrange the filters like this:

- Date: using special words like today, yesterday, week (current), month (current) or passing a iso-date (yyyy-mm-dd).
- Subject: any keyword present in the title.

**Comment by bmeneguele** [comment]
Ahh ok, got it! Well, that's fine by me then considering the filtering feature.
Are you planning to work on that or were you assigned just for the first part of the issue, before @luizdepra reopen it? I mean, if you're not planning any time soon would you mind if I take over it?

**Comment by julianolf** [comment]
Back them I thought about split in two different issues, change this one to just print the page title so it could be closed, and create a new one to store the link plus the title and the date/time, but now I think it is not necessary.

I can finish this but I would like to first decide if we are going to change from Redis to another simpler database like SQLite or not, there is an issue to do that (#7).

**Comment by bmeneguele** [comment]
Although I agree it's not necessary to split I think it would be better.. but nhaa.. your call :D
Now, about Redis vs SQLite-like dbs, to be honest I don't really see why Redis is being used since we don't make use of its real features/advantages, unless we're planning something pretty huge to mr_roboto in the future :laughing:. But AFAICS SQLite would be enough and even more appropriate considering project's current situation.

**Comment by julianolf** [comment]
IIRC the reason to use Redis was because by the time we started this project the storage plugin just supported two "backends", a text file or Redis, and the idea of using a simple text file doesn't seemed to fit our needs. But we've talked about change to a better and simpler solution. Honestly, I don't know why irc3's storage plugin does not support SQLite.

**Comment by bmeneguele** [comment]
Ok! I see. Well I would have chosen Redis in this situation as well :). And per issue #7 I agree in changing it to dataset/SQLite.
