### ISSUE TITLE
Bot versioning and release

### ISSUE THREAD

**Issue by bmeneguele** [meleca/mr-roboto#64]
I think we're at a good shape to start shipping our bot as a "release". I'm not calling it v1.0 or something like that, but at least set some milestones to hold major feature/bugfixes changes that might happen. Why is it useful for our project? TBH, not much, but keep track of changes in a version manner helps everyone other than us to maintain their "production" environment.

My suggestion is to start using something like [semantic versioning](https://semver.org/), **X.Y.Z**, where:

**Z**: bumps when a bug is completely solved;
**Y**: bumps when a feature is implemented, but not changing nothing architectural;
**X**: bumps when an architectural change happens, but it be a huge feature changing the way app works/behaves or new tools are implemented (e.g the redis->sqlite + sqlalchemy + alembic + ... change we had few days ago).

With that we don't need to update the bot every time a PR happens, but just when several PRs together solves a complete issue. And in the technical side we can maintain the version on Makefile and if necessary fetch it from within bot's code.

@julianolf @luizdepra, what do you guys think?

**Comment by julianolf** [comment]
It looks great for me.

My only question is, when are we releasing the version 1? When we finish all existing issues?

**Comment by bmeneguele** [comment]
Yep, that's what I had in mind =)
